version: '3.8'

networks:
  proxy-network:
    external: false
    name: proxy-network

services:
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-main-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/sites-available/nginx.conf:ro
    networks:
      - proxy-network
    restart: unless-stopped
    depends_on:
      - remove-bg-backend

  remove-bg-backend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/remove-bg-backend:latest
    container_name: remove-bg-backend-container
    expose:
      - "5000"
    networks:
      - proxy-network
    restart: unless-stopped 