name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "nginx/**"
      - "docker-compose.yml"

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.8"

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build-and-deploy:
    needs: install-dependencies
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.TOKEN_GITHUB }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/remove-bg-backend:latest
          cd backend
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Copy docker-compose and nginx configs
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: "docker-compose.yml,nginx/nginx.conf"
          target: "remove-bg-app/"

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Login to registry
            echo "${{ secrets.TOKEN_GITHUB }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

            # Pull latest images and start
            docker compose pull
            docker compose up -d

            # Show status
            echo "=== Deployment Status ==="
            docker compose ps
            echo "=== Nginx Config Test ==="
            docker exec nginx-main-proxy nginx -t || echo "Nginx test failed"
            echo "=== Reloading Nginx ==="
            docker exec nginx-main-proxy nginx -s reload || docker restart nginx-main-proxy

            # Clean up old images
            docker image prune -f
